42ity/fty-nut

ci_build.sh, project.xml, src/Makemodule-local.am, src/fty-nut.service.in
Solution: fix the project files
=> Problem: we require CZMQ v3.0.2 API

src/nut.cc
Solution: Add missing arguments.
Signed-off-by: Jana Rapava <janarapava@eaton.com>
=> Problem: fty-nut does not compile.

src/fty_nut_configurator_server.cc, src/nut.cc, src/nut_configurator.cc, src/nut_configurator.h
Solution: extend auto-configuration agent of ATS configuration capability
=> Problem: NUT auto-configuration is not working with ATS

src/nut_configurator.cc
Solution: Adapt the driver selection algorithm
Eaton ATS16 PDU supports both XML/PDC and SNMP. However, proper XML/PDC support
is not implement in the driver (and may not be optimal).
=> Problem: Eaton ATS16 is detected with XML/PDC

src/nut_device.cc
Solution: Check some .L3. variables and decide by its existence
=> Problem: Some 3phase ups NUT drivers doesn't provide phase number

src/mapping.conf
Solution: Add it into maping file
=> Problem: ATS voltage and input is not monitored

src/alert_actor.cc, src/alert_device.cc, src/alert_device.h, src/alert_device_list.cc, src/alert_device_list.h, src/nut_agent.cc, src/sensor_device.cc
Solution: add ttl to device alerts, fix encode usage
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>
=> Problem: build fails with new fty-proto

src/mapping.conf
=> Problem: travis test fails and produces core dump

src/nut_agent.cc, src/nut_device.cc, src/nut_device.h
Solution: Change the approach and use string instead of number
=> Problem: Text metrics like ats input status can't be produced

src/mapping.conf
=> Problem: ups real power is not mapped correctly

src/nut_device.cc
Solution: computation corrected
=> Problem: DC total power is not computed from correct values

project.xml
Solution: fix it
Signed-off-by: Arnaud Quette <arnaud.quette@free.fr>
=> Problem: typo in project.xml

src/fty_nut.cc
Solution: make older OSes happier and slightly optimize CLI argument processing.
=> Problem: portability of this component can be improved

src/mapping.conf
=> Problem : firmware version is missing

src/mapping.conf
=>  Problem: Mapping does not have input.phase.shift

src/mapping.conf
=> mapping.conf : fix inconsistent whitespace

src/alert_device.cc, src/nutscan.cc
Solution: try to avoid them, and add debug traces to research them
=> Problem: we have empty scans producing invalid ups.conf entries

src/fty_nut_configurator_server.cc
Solution: Handle update/create of nonactive device as delete
=> Problem: Autoconfig insists on configuring of nonactive devices

src/nut_device.cc
=> Problem: load value is not rounded

src/mapping.conf, src/nut_agent.cc
=> Problem : IPM needs more metrics and inventory data

src/mapping.conf, src/nut_agent.cc
=> Problem : edpu apparent power is not mapped

src/mapping.conf
=> Problem : ups apparent power is not mapped

src/mapping.conf
Solution: Map feed name and color for the first input
=> Problem: Need to publish feed information

src/mapping.conf
Solution: Map input.power.nominal
=> Problem: Need to publish ePDU nominal power

src/nut_agent.cc
=> Problem: Unit for delays is missing

src/nut.cc, src/nut.h, src/sensor_actor.cc, src/sensor_device.cc, src/sensor_device.h, src/sensor_list.cc, src/sensor_list.h
=> Problem: contact status for gpio located in EMP001 is not sent 

README.md
=> Problem: README missing

src/sensor_list.cc
=> Problem: debug message processed even if sensor location is ok

README.md
=> Problem: message samples missing

README.md
=> Problem: Some typo errors

src/sensor_device.cc
=> Problem: handle more states of gpios then just open/close

src/sensor_device.cc
=> Problem: need to improve debug message

src/sensor_device.cc, src/sensor_device.h, src/sensor_list.cc, src/sensor_list.h
=> Problem: children get overwritten

src/alert_device_list.cc, src/nut_device.cc, src/sensor_device.cc, src/sensor_list.cc
Solution: Reword daisychain messages
=> Problem: Need to fix message to match LCD menu on ePDUs

include/fty_nut.h, src/actor_commands.cc, src/alert_actor.cc, src/fty_nut.cc
Signed-off-by: Daviet, Nicolas <NicolasDaviet@eaton.com>
=> Problem: when polling timer change, fty-nut don't change his polling time

src/alert_actor.cc
Solution: I noticed poller is used in a wrong way, so I added proper timer for publishing.
=> Problem: fty-nut seems to have problems sending alerts, probably an performance issue

src/fty_nut_configurator_server.cc, src/fty_nut_server.cc
Solution: separated poller from timer for periodic polling
=> Problem: periodic poller is based on mlm poller function that expires only when there are no messages

src/mapping.conf
Solution: Comment interrop variables
Many variables were added for interrop, leading to a huge increase of data
produced on the bus. Disable this temporarily, since interrop is not released
=> Problem: Need to lower stress on malamute

src/mapping.conf
=> Revert "Problem: Need to lower stress on malamute"

src/nut_configurator.cc
Solution: Detect these as PDU for NUT configuration
=> Problem: Emerson ePDUs need with synchronous flag

src/nut.cc
We have seen cases where the state file is full of "delete" messages.
One possibility is that devices appear while fty-nut is not running and
it only sees the deletion. In such case, the block handling an unknown
asset in nut_put would trigger.
=> Do not store "delete" messages in the state file

src/alert_actor.cc, src/nut_mlm.h
I forgot to connect it.
Fixes: 96d189fa064f ("Simplify malamute connection setup")
=> Fix the alert actor mailbox client setup

src/asset_state.cc
=> Problem : handling properly nonactive asset

include/alert_actor.h, src/actor_commands.cc, src/actor_commands.h, src/alert_actor.cc, src/fty_nut.cc, src/fty_nut_configurator.cc, src/fty_nut_server.cc, src/sensor_actor.cc
=> Problem: fty-nut still uses old verbose approach

src/mapping.conf
=> Problem: Mapping for realpower on output is missing

src/nut_configurator.cc, src/nutscan.cc
=> Problem: namespace for subprocess changed

src/mapping.conf
Signed-off-by: François-Régis Degott <eaton@debian>
- needed for MASS upgrade
=> add ups.firmware.aux entry in mapping.conf

src/asset_state.cc, src/sensor_device.cc, src/sensor_device.h, src/sensor_list.cc
Solution: don't monitor invalid sensors
=> Problem: nut sensors are not monitored properly

src/fty_10_agent-nut, src/nut_configurator.cc, src/nut_configurator.h
=> Problem systemctl reload-or-restart nut_server may hang on IPC

src/fty_nut_configurator_server.cc
Solution: prevent licensing limitation trigger reconfiguration
S/S
=> Problem: assets are reconfigured every time new licensing message is received

src/alert_device.cc
=> Problem: we need to mark strings in nut rule for translate

src/alert_device.cc
Signed-off-by: Jana Rapava <janarapava@eaton.com>
=> Wrong variable designators in NUT rule.

src/alert_device.cc
Signed-off-by: Jana Rapava <janarapava@eaton.com>
=> (S/M) NUT rule is invalid JSON.

src/ups_status.cc, src/ups_status.h
=> On test is the same as CALibration

src/nut_device.cc
Querying device variables in bulk significantly improves throughput. A test scenario with 300 ePDUs reduced the processing time duration from 15 seconds down to about 1 second.
This depends on a new method in libnutclient (https://github.com/networkupstools/nut/pull/654).
=> Improve performances with new libnutclient method

src/fty_nut_configurator_server.cc
Solution: Only consider daisychain host
(cherry picked from commit 6cf416e04abcaf7af73b6531ce2f25cc348b5570)
=> Problem: Daisychain devices are configured

src/fty_nut_server.cc, src/nut_agent.cc
Signed-off-by: barraudl <lilianbarraud@eaton.com>
=> Remove the malamute publishing for metrics

src/fty_nut_command.cc, src/fty_nut_command_server.cc
Depends on a backport of https://github.com/networkupstools/nut/pull/673.
=> Implement tracking commands

src/fty_nut_command.cc, src/fty_nut_command_server.cc
Signed-off-by: Jean-Baptiste Boric <Jean-BaptisteBORIC@Eaton.com>
=> Add safety net in case of closed NUT socket

src/alert_actor.cc, src/alert_device.cc
Solution: fixed rule for fty-alert-engine
=> Problem: changed rule format for fty-alert-engine

src/alert_device.cc
Solution: fixed rule for fty-alert-engine (all rules must have evaluation functiton now), fixed json format + minor visual fixes, for review ignore whitespace changes
=> Problem: sent rules are not supported by fty-alert-engine

src/nut_agent.cc
Solution: Q&D fix added one more hardcoded state
@aquette you may want to provide better fix later
=> Problem: Internal failure state is not properly recognized

src/nut_agent.cc
See #193 for master PR and discussion.
=> Backport: Q&D fix for Internal fault issue IPMVAL-1108

src/asset_state.cc, src/asset_state.h
Signed-off-by: Clement Perrette <clementperrette@eaton.com>
=> Disable check of licence for monitoring and monitor all active devices

src/alert_device.cc, src/sensor_device.cc, src/sensor_list.cc
Solution: Add support for indexed sensors collection
=> Problem: Need to support EMP002 with daisychain

src/sensor_device.cc
Sensor may not be present (or connected). However, the values
(temperature, humidity, ...) are still available, but should not be
considered
=> SNMP Eaton EMP002: handle sensor presence

src/fty_nut_command_server.cc
Actual implementation of power actions based on power topology.
=> Shutdown asset power sources step #2

src/fty_nut.cc
=> Common logging standard

src/nut_configurator.cc
Solution: List all known MIBs to detect supported ATS
=> Problem: ATS detection / configuration is a crap

src/nut_agent.cc
* IPMVAL-1889 fix
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
=> Problem: IPMVAL-1889 - empty status.ups on data-stale

src/nut_agent.cc
hotfix
* status.ups metric: ttl increased
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
=> Problem: status.ups metric ttl must be increased- IPMVAL-1889

src/nut_configurator.cc
Signed-off-by: Jean-Baptiste Boric <Jean-BaptisteBORIC@Eaton.com>
=> Fix ePDU monitoring (2.2.0)

src/ups_status.cc
Signed-off-by: Jean-Baptiste Boric <Jean-BaptisteBORIC@Eaton.com>
=> Forward-port IPMVAL-1889 fix from 2.1.0

src/asset_state.cc, src/asset_state.h, src/nut_configurator.cc, src/ups_status.cc
PRs to merge before merging this PR :
=> Forward-port fixes from 2.2.0

src/nut_agent.cc, src/ups_status.cc, src/ups_status.h
* power.status@ups integration
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
=> PQSWMBT-4544 - power.status@ups integration

include/fty_nut_command_server.h, src/fty_nut_command_server.cc
Not as clean as it could (or should) be, but that'll do for now.
=> Automatic group support

lib/src/nut_agent.cc, lib/src/nut_agent.h
* light review
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
=> IPMPROG-325 - nut_agent.cc light review
