- fty-nutconfig
- src/alert_actor.cc
- src/fty-nut.conf.in
- src/fty-nut.service.in
- src/fty_nut_configurator_server.cc
- src/fty_nut_server.cc
- src/nut_configurator.cc
- src/sensor_actor.cc
Solution: Hardcode old names and leave comments to change them back later
Bonus question: SHOULD this be done? Or do we want to change paths? Opinions differ in various components...
> Problem: Old FS pathnames should be used to upgrade in-place

- fty-dmf
- fty-nutconfig
- src/alert_actor.cc
- src/fty-nut.conf
- src/fty-nut.service.in
- src/fty_nut.cc
- src/fty_nut_configurator_server.cc
- src/fty_nut_server.cc
- src/nut_configurator.cc
- src/sensor_actor.cc
Note: review desired - I am not yet certain we actually generate these paths in preinstall etc. (and/or that script should be updated to do so).
Also this does not touch messaging strings for agents this one communicates with, so may need PRs similar to those that happen in other repos - to align naming for intertalk.
> Apply bios=>fty renaming for paths (wave one)

- src/fty_nut_configurator_server.cc
Solution: path to the state file corrected
Signed-off-by: Barbora Stepankova <barborastepankova@eaton.com>
> Problem: nut configurator cannot find fty-autoconfig state file

- src/nut_agent.cc
Solution: check if arguments for streq are not NULL
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>
> Problem: fty-nut segfaults in testing environment

- src/nut_agent.cc
> Problem: input has no units

- src/mapping.conf
Solution: Add it to maping file
> Problem: ATS input frequency & voltage status is not propagated

- src/nut_device.cc
Solution: load the file during make check to ensure syntax is valid
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>
> Problem: mapping file broken as a result of backports

- src/alert_device.cc
Solution: Send them to the propper agent (renamed to fty-alert-engine)
> Problem: Internal threshold rules are not visible in UI

- src/alert_actor.cc
Solution: Fix the name in test too
> Problem: Old alert engine name in test

- src/fty-nut.conf
- src/sensor_list.cc
Solution: Create it via tmpfiles
> Problem: /var/lib/fty/fty-autoconfig directory needed by agent

- src/sensor_device.cc
Metric message for humidity, published by fty-nut's sensor actor,
does have 'port' corretly set in aux field:
```
stream=_METRICS_SENSOR
sender=agent-nut-sensor
subject=humidity.0@ROZ.UPS33
D: 17-05-02 11:35:11 FTY_PROTO_METRIC:
D: 17-05-02 11:35:11     aux=
D: 17-05-02 11:35:11         port=0
D: 17-05-02 11:35:11     time=1493724911
D: 17-05-02 11:35:11     ttl=60
D: 17-05-02 11:35:11     type='humidity.0'
D: 17-05-02 11:35:11     name='ROZ.UPS33'
D: 17-05-02 11:35:11     value='36.5'
D: 17-05-02 11:35:11     unit='%'
```
however the same message for temperature does not:
```
stream=_METRICS_SENSOR
sender=agent-nut-sensor
subject=temperature.0@ROZ.UPS33
D: 17-05-02 11:35:11 FTY_PROTO_METRIC:
D: 17-05-02 11:35:11     aux=
D: 17-05-02 11:35:11     time=1493724911
D: 17-05-02 11:35:11 …
```
> PROBLEM: field 'port' is missing in message aux

- src/nut_device.cc
Solution: Calculate power from voltage and current if not present.
Load is then calculated using max_power ext attribute as the value
of 100% (i.e. load = power/max_power*100%)
> Problem: BIOS-3634 Power-device load calculation

- src/nut.cc
Solution: nut.c : revise and comment usage of size_t vs. uint64_t, and rearrange a bit of shared code
Note: passes with both CZMQ versions, see https://travis-ci.org/42ity/fty-nut/branches
This is part of revision of multiple component repos, including PRs:
* https://github.com/42ity/fty-kpi-power-uptime/pull/26
* https://github.com/42ity/fty-nut/pull/47
* https://github.com/42ity/fty-alert-list/pull/26
* https://github.com/42ity/fty-metric-cache/pull/25
> Problem: recent czmq4-related fixes followed different patterns

- src/nut.cc
Should fix this report in OBS:
````
[ 2397s]   CXX      src/src_libfty_nut_la-nut.lo
[ 2402s] In file included from src/fty_nut_classes.h:104:0,
[ 2402s]                  from src/nut.cc:29:
[ 2402s] src/nut.cc: In function 'int nut_load(nut_t*, const char*)':
[ 2402s] src/logger.h:75:66: error: format '%llu' expects argument of type 'long long unsigned int', but argument 7 has type 'off_t {aka long int}' [-Werror=format=]
[ 2402s]          log_do((level), __FILE__, __LINE__, __func__, __VA_ARGS__); \
[ 2402s]                                                                   ^
[ 2402s] src/logger.h:80:9: note: in expansion of macro 'log_macro'
[ 2402s]          log_macro(LOG_DEBUG, __VA_ARGS__)
[ 2402s]          ^
[ 2402s] src/nut.cc:553:9: note: in expansion of macro 'log_debug'
[ 2402s] …
```
> nut.cc : printing of off_t as PRIu64 complains in ARM builds

- src/mapping.conf
Solution: Add outlet.#.type to the mapping
> Problem: Outlet physical is not published

- src/mapping.conf
> Problem: outlet.group.#.phase mapping is missing

- src/mapping.conf
> Problem: outlet.#.name mapping is missing

- src/mapping.conf
Solution: Use outlet.group.#.label
Outlets use label for the "friendly" name and name for the static (electrical)
name. Modify our mapping to ensure coherence
> Problem: outlet.group.#.name is not coherent

- src/mapping.conf
> Problem: Outlet group color is missing

- src/mapping.conf
Solution: Add these
current and active power were missing, along with apparent power and voltage
> Problem: Some outlet group data are missing

- src/mapping.conf
> Problem: Outlet group static name is missing

- src/nutscan.cc
Solution: Report SUCCESS for exit-code 0 even if there was something printed on stderr
> Problem: Misleading "FAILED" nut-scanner with exit-code 0

- src/nutscan.cc
Solution: Add the -q option
Not running in quiet can generate false positive errors
> Problem: nut-scanner is not in quiet mode

- fty-nutconfig
Solution: bump the default timeout when generating ups.conf
(Note: NUT default is 45 sec)
> Problem: NUT networked driver init can exceed default timeout

- src/fty-nut.cfg.in
- src/fty_nut.cc
- src/fty_nut_configurator_server.cc
Problem: asset subtype integer values are hardcoded
Solution: Use the existing asset_subtype enum
Problem: verbose mode is not verbose enough
Solution: Enable LOG_DEBUG when verbose is set
Problem: Configuration file is not processed
Solution: Handle configuration file
Problem: NUT polling interval is not configurable
Solution: Make it configurable
> Problem: various problem

- src/alert_device.cc
Just a trivial adaptation to a fty-proto change.
Signed-off-by: Michal Marek <MichalMarek1@eaton.com>
> Change the action field of alert messages to zlist

- src/alert_device.cc
- src/nut_configurator.cc
["EMAIL", "SMS"] -> [{"action": "EMAIL"}, {"action": "SMS"}]
in the generated rules.
Signed-off-by: Michal Marek <MichalMarek1@eaton.com>
> Change the json rule format to allow for future extensions

- src/fty_nut_server.cc
> Problem: malamute client is set twice as consumer

- fty-nutconfig
Solution: Use drop-in configuration to customize nut-driver systemd timeout, to match 42ity bundled ups.conf maxstartdelay
> Problem: nut-driver@.service instances time out before NUT maxstartdelay

- src/alert_actor.cc
- src/alert_device.cc
Solution: Wait for confirmation (which has a nice benefit of getting rid of one memleak in Malamute.)
Signed-off-by: Jana Rapava <janarapava@eaton.com>
> Problem: NUT alerts are sent before fty-alert-engine adds NUT rules.

- src/nut_configurator.cc
Solution: Detect these as PDU for NUT configuration
(cherry picked from commit 4f76402ef5bfed3f56b22c6705b5052ac3f92e87)
> Problem: Emerson ePDUs need with synchronous flag

- src/alert_device.cc
Solution: flag 'rulePublished' is also set then fty-alert-engine sends "ALREADY_EXISTS"
>  Problem: fty-nut does not process responds from fty-alert-engine correctly 

- src/alert_actor.cc
- src/alert_device.h
- src/alert_device_list.cc
Unlike the sensor actor and the NUTAgent, the alert actor maintains a
persistent view of the devices. To avoid accessing pointers to Asset
objects that have been deleted, use a shared_ptr to refer to the Asset
object.
> Fix a use-after-free crash in the alert actor

- include/fty_nut_configurator_server.h
- src/asset_state.cc
- src/asset_state.h
- src/fty_nut_configurator.cc
- src/fty_nut_configurator_server.cc
- src/fty_nut_server.cc
- src/nut_configurator.cc
- src/nut_configurator.h
- src/nut_mlm.h
- src/state_manager.h
This pull request removes the json-formatted state file code that never worked and migrates fty-nut-configurator to the StateManager class. The new code makes sure that /var/lib/fty/fty-nut/devices and in turn /etc/nut/ups.conf is in sync with the StateManager's view of assets, even if the agent is restarted. It should be even possible to merge fty-nut-configurator into fty-nut and use a shared StateManager,  but let's not be that intrusive.
> Rework fty-nut-configurator state handling

- src/fty_nut_configurator_server.cc
This PR fixes a use-after-free which happened when assets got deleted. Also, it makes sure that existing assets are processed right after startup.
> fty-nut-configurator regression fixes

- src/subprocess.cc
- src/subprocess.h
Make sure that whenever we close one of the pipe ends, we set it to
PIPE_DEFAULT to avoid closing it again in the destructor. Otherwise, we
could race with a different thread that calls open() or socket()
in-between and gets assigned the same file descriptor.
Signed-off-by: Michal Marek <MichalMarek1@eaton.com>
> subprocess: Do not close the same file descriptor twice

- src/asset_state.cc
- src/asset_state.h
- src/fty_nut_configurator_server.cc
- src/fty_nut_server.cc
- src/state_manager.cc
- src/state_manager.h
Get current limitation from etn-licensing and limit the number of power devices for which metrics are published. fty-nut-configurator still works with all devices, so as not to lose configuration when a license expires and before it is renewed.
> Implement licensing limitation

- src/fty_nut_configurator_server.cc
Whenever the underlying asset information changes, we must reconfigure
the device.
> Fix processing of asset updates in fty-nut-configurator

- src/asset_state.cc
- src/state_manager.cc
The asset names are unique, so if it is a sensor or a power device, we
will find it in one of the maps.
> Process asset delete messages even if there is no aux field

- src/fty_nut_server.cc
I spent an hour debugging why fty-nut is not sending any metrics... Only
to find out that my license expired.
> Print the number of initial devices and sensors in verbose mode

- fty-nutconfig
- src/fty_nut_configurator_server.cc
- src/nut_configurator.cc
- src/nut_configurator.h
In the main loop, process incoming messages as long as there are any and
call Autoconfig::onPoll() only if there is nothing left in the queue.
In NUTConfigurator::configure() and NUTConfigurator::erase(), only
update the configuration snippets and do the restart the services after
all changes in the current round have been processed. This provides a
considerable speed up when importing large number of devices.
> fty-nut-configurator: Run systemctl actions in batches

- src/mapping.conf
(cherry picked from commit 32cc8c53c23426e6cd4bfa22f7914e2ad5085f37)
> Problem: Mapping for realpower on output is missing

- src/nut_configurator.cc
see https://github.com/42ity/fty-nut/pull/139
> backport : systemclt sequence is not optinized

- src/nut_configurator.cc
Problem 1 : this bellow sequence may does 1 start, 1 stop, 1 start of the driver which is not optimized.
systemctl ("enable",  std::string("nut-driver@") + name);
systemctl ("restart", std::string("nut-driver@") + name);
systemctl ("reload-or-restart", "nut-server");
It is due to dependency with nut-server.service which wants nut-driver.target.
Solution : adapt the sequence to ensure only one start is done
systemctl ("restart", std::string("nut-driver@") + name);
systemctl ("enable",  std::string("nut-driver@") + name);
systemctl ("reload-or-restart", "nut-server");
-------------------------------------------------------------------------------
Problem 2 : this bellow sequence may hang fty-nut-configurator,
updateNUTConfig(); …
> Problem : systemclt sequence is not optinized

- src/fty-nut-command.service.in
Small fixup to ensure NUT users are created before we try to start fty-nut-command.
> Start fty-nut-command after nut-server

- fty-nutconfig
- src/nut_configurator.cc
- src/nut_configurator.h
Follow-up for https://github.com/42ity/nut/pull/66
This should avoid potential clash of activities managing system services, and impose a time limit on occasionally freezing `systemctl` operations (which sometimes breaks even without this clash) from NUT side, and remove blockage in fty-nut service (while it waits indefinitely for `systemctl`) so it can just generate the new config and go on processing the messages.
Note: currently this is implemented as a potentially configurable (no methods to do so) run-time flag, rather than ripping the functionality out right away, so we can test how well it behaves.
>  nut_configurator : disable direct management of systemd services 

- src/asset_state.cc
- src/asset_state.h
- src/fty_nut_configurator_server.cc
- src/fty_nut_server.cc
- src/state_manager.cc
Problem  : fty-nut-configurator calls AssetState::updateFromProto but missed to free the associated proto payload.
Solution : free  the proto payload.
Problem  : There are 2 versions of the function AssetState::updateFromProto, one which free the msg, and the other one which not free it. It's ambigious.   
Solution : use a different naming for different behaviour.
> Problem ; fty-nut-configurator has a memory leak

- fty-nutconfig
Minimize the chance that this happens by making FS operations with `ups.conf` in `fty-nutconfig` atomic (so the file is not processed while half-written); also reduce flash wear by avoiding needless writes (though just in case, do still call nut-driver-enumerator in such case, to cover up whatever we might miss before).
Complements the changes in https://github.com/42ity/nut/pull/69
> Problem: nut-driver-enumerator can miss changes of ups.conf happening WHILE it runs

- src/mapping.conf
- src/nut_agent.cc
- src/ups_status.cc
- src/ups_status.h
Solution : Add "On Test" (OT) to ups.status when ups.test.result=="in progress"
> Problem : status.ups doesn't include test in progress

- fty-nutconfig
Solution: handle all exits from fty-nutconfig script with a cleanup of the temp file
Thanks @jeffdegott for catching this issue.
@jana-rapava @EldoreiJK : this should get into 1.5.0 after testing too.
> Problem: /tmp is full of  tmp nutconfig.xxxxxxx

- src/alert_device.cc
- src/alert_device_alert.h
Solution: Track if an existing DeviceAlert entry was changed during a scan.
See #172 for details. Validate carefully since this potentially changes behavior (should not, looking from outside) :) In particular, changes in accessible device sets or changes of their published capabilities SHOULD cause republish of the new data; rescans of unmodified device sets of unmodified devices SHOULD NOT be republished and later ignored by receiver, wasting time and impacting performance.
> Problem: Same rules can get republished after a scan

- src/alert_device.cc
Solution: variable should be spelled variable*s*
> Problem: Alert rules are malformed

- src/alert_device.cc
- src/alert_device_alert.h
This should keep fty-alert-engine from processing already exisiting rules and hopefully improve the metrics processing performance.
> Backport 1.5.0

- fty-nutconfig
This script recreates `/var/lib/fty/fty-nut/devices` and sets permissions, without this the system can no longer configure NUT drivers after this is called.
Release branch is not concerned.
> Fixup permission inside fty-nutconfig

- src/nut_device.cc
Split-phase UPSes have two phases and fty-nut crashes with these.
> Fix detection of 3-phase devices.

- include/fty_nut_command_server.h
- src/fty_nut_command_server.cc
This, along with some functional programming results in a massively simplified source code for fty-nut-command. Also takes advantage of functional programming style to add some unit tests.
Lots of code moved around, not much code actually added or deleted.
Depends on:
- https://github.com/42ity/fty-common-messagebus/pull/10
- https://github.com/42ity/fty-common-dto/pull/13
> Refactor with messagebus::Dispatcher

- src/nut_device.cc
Split-phase UPSes have two phases and fty-nut crashes with these.
Backport for IPM-2.0.1, PR in stand-by until we decide how to proceed about that.
> [DO NOT MERGE] Fix detection of 3-phase devices.

- src/nut_agent.cc
- using std::string::c_str() caused leak on zhash_insert()
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
> Add missing zhash_autofree

- src/asset_state.cc
- src/asset_state.h
- src/nut_configurator.cc
- src/nut_configurator.h
This PR makes fty-nut-configurator aware of the first endpoint in an asset and configures it for NUT if it's recognized (currently SNMP and NetXML types). For backwards compatibility, if an asset has no endpoints it will trigger the legacy configuration codepath, converts the result to an endpoint and updates the asset accordingly.
It is a minimally-intrusive set of modifications since fty-nut-configurator was not really designed for this in the first place. We'll need a real overhaul of this agent eventually along with the rest of fty-nut so that the following is properly handled:
- Multiple endpoints configurations
- Multi-homing
- Daisy-chaining not dependent on the host being active to work
- Endpoint connectivity status
- Fallbacks in case of communication lost
- ...
> [DO NOT MERGE] Endpoint logic for fty-nut-configurator

- src/nut_configurator.cc
Note: logically depends on https://github.com/42ity/fty-common-nut/pull/27
Also: asset extended property keytag `endpoint.1.nut_powercom.secw_credential_id` is too long for our current DB schema (max. 40 characters currently), it is in the process of being upgraded by @perrettecl.
> Add nut_powercom endpoint support

- src/fty_nut_command_server.cc
This is very, very wrong... fty-nut-command shouldn't second-guess its requests like that.
> Throw out non-server assets from automatic groups

- README.md
- lib/src/asset_state.h
- fix deb11 build (missing includes)
Note: 
- make coverage: seems we have a build issue (unresolved symbols, pthread_mutex_clocklock())
- lib tests: one test is disabled (sensor_list)
> Debian11 build
